### ISSUE TITLE
Can this handle global functions?

### ISSUE THREAD

**Issue by alessandrotesoro** [TypistTech/imposter#148]
Hi there, I'm looking at ways to prefix one specific package in my project. The package also brings it's own global functions that are all prefixed with "tr_", they're not functions that have been namespaced. So ideally I'd like to "prefix the prefix" eg: from "tr_" to "new_tr_".

Can Imposter also prefix global functions or is it only restricted to classes? 

Thank you :)

**Comment by TangRufus** [comment]
No, functions, both global and namespeced, are not supported.

Reason: imposter's ulgy regex cannot distingish class methods and functions:

```php
function my_function() {}

class ABC
{
  function my_method() {}
}
```

If https://github.com/TypistTech/imposter/issues/101 is implemented, we might able to support namespeced functions.
