### ISSUE TITLE
Almost the last part of a modern WordPress development

### ISSUE THREAD

**Issue by matzeeable** [TypistTech/imposter#149]
Hi!

Here is Matthew from Germany. Believe me, in many years I have gained a lot of experience regarding modern development in the ecosystem of WordPress. It is always difficult for developers to maintain multiple plugins. I have an Open-Source solution for all developers out there: [WP React Starter](https://github.com/devowlio/wp-react-starter/). WP React Starter is built on top of all modern web development tools ported to the WordPress economy.

**Why do I open this issue?**

I just ran into the problem that there can be different dependency versions between plugins (in relation to Composer). I have found your solution and think:

**Lets marriage `imposter` with `wp-react-starter`**

Are you open to work together to make this work? Due to the fact that WP React Starter is working a lot with `trait`s I need to get this work before I implement it into my open source project. Reference: https://github.com/TypistTech/imposter/issues/111

Please let me know what you think!

**Comment by TangRufus** [comment]
`wp-react-starter` looks awesome.

I presume you want to add imposter to the plugins (https://devowlio.gitbook.io/wp-react-starter/advanced/create-package). Am I correct?

Considerations:
- Adding `imposter` introduces complexity
- If you control all the plugins, making all plugins use the same package version is a better choice (i.e: let the root composer.json determine which version to install)
- Imposter is far from perfect, we might need to invesgate a real PHP praser, see: https://github.com/TypistTech/imposter/issues/101

Anyways, let a comment here if you encounter difficulties integrating `imposter` with `wp-react-starter`

**Comment by matzeeable** [comment]
Hi again!

Thanks for your words. The last few days I intensively worked on scoping WordPress plugins and found an ultimative way of doing this. I introduced [PHP-Scoper](https://github.com/humbug/php-scoper) to my boilerplate as `imposter` did not work for me (one reason was #151).

If you or someone else is interested, the boilerplate documentation can be found [here](https://devowlio.gitbook.io/wp-react-starter).

@TangRufus Behind the scenes, the most important part of scoping are stubs: https://devowlio.gitbook.io/wp-react-starter/php-development/add-classes-hooks-libraries#stubs

Regards,
Matthew 🙂
