### ISSUE TITLE
Namespace not added to non-aliased namespaces

### ISSUE THREAD

**Issue by Dartui** [TypistTech/imposter#377]
Hello. I have found error with prefixing non-aliased namespaces. Let's take GuzzleHttp/Client as an example:

<img width="553" alt="obraz" src="https://user-images.githubusercontent.com/2657856/128603548-43db7321-80f2-4f25-85aa-73d557188256.png">

And this is how this class looks after running Imposter:

<img width="529" alt="obraz" src="https://user-images.githubusercontent.com/2657856/128603521-9b83057d-8129-46ce-b821-387776dbdebc.png">

As you can see, `\Psr\Http\Client\ClientInterface` is not prefixed with given namespace, so it throws fatal error about missing class.

**Comment by tangrufus** [comment]
Why the original `ClientInterface` is `\Psr\Http\Client\ClientInterface` instead of `\GuzzleHttp\ClientInterface`?

**Comment by Dartui** [comment]
The `ClientInterface` is actually `\GuzzleHttp\ClientInterface` (or `\My\App\Vendor\GuzzleHttp\ClientInterface` after using Imposter). That's why FQCN `\Psr\Http\Client\ClientInterface` is used to not make name conflicts.

They probably could rename it while aliasing, e.g. `use Psr\Http\Client\ClientInterface as PsrClientInterface`, but they decided to use it directly. Unfortunately Imposter does not handle it.

**Comment by tangrufus** [comment]
That is correct. Imposter only finds class names after the `use` keyword.

https://github.com/humbug/php-scoper might be a better choice for you.

**Comment by Dartui** [comment]
That's fair, thanks for response
