### ISSUE TITLE
Return value of TypistTech\Imposter\ArrayUtil::flatten() must be of the type array, null returned

### ISSUE THREAD

**Issue by Luc45** [TypistTech/imposter#76]
I am receiving the following error when trying to run `$imposter->run()`:

`Fatal error: Uncaught TypeError: Return value of TypistTech\Imposter\ArrayUtil::flatten() must be of the type array, null returned in /home/vagrant/dev/tmp/imposter/vendor/typisttech/imposter/src/ArrayUtil.php on line 24`

The debug callback of xDebug points that `Config::getAutoloadPaths()` is the method calling the faulty `ArrayUtil::flatten()`:

```php
    /**
     * @return string[]
     */
    private function getAutoloadPaths(): array
    {
        $autoload = $this->get('autoload');

        return ArrayUtil::flattenMap(function ($autoloadConfig) {
            return $this->normalizeAutoload($autoloadConfig);
        }, $autoload);
    }
```

Looking at ArrayUtill::flatten(), I see that I am receiving an empty array for some reason, so I've changed it to:
```php
    public static function flatten(array $array): array
    {
        if ( ! empty($array)) {
            return call_user_func_array('array_merge', $array);
        } else {
            return $array;
        }
    }
```

And now it runs without error, but I'm afraid that it might break something or not work as intended, because it changed just 2 files in vendor folder. I don't know if I did something wrong, here's my steps:

1. I've created a temporary folder where I ran `composer require typisttech/imposter`
2. I've pointed imposter to my plugin's folder
3. Added the "extra" session to my plugin composer.json file:

```json
{
  "autoload": {
    "psr-4": {
      "Trial\\": "src"
    },
    "files": [
      "src/Container/Trial.php",
      "vendor/lucatume/wp-routes/wp-routes.php"
    ]
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/lucatume/wp-routes"
    }
  ],
  "require": {
    "lucatume/di52": "^2.0",
    "lucatume/wp-routes": "dev-master"
  },
  "extra": {
    "imposter": {
      "namespace": "Trial\\Vendor"
    }
  }
}
```

4. Tried to run imposer both in CLI and web. Got errors the above. I have PHP 7.2.1.

I am doing something wrong?

Thanks

**Comment by TangRufus** [comment]
Because the required dependencies don't have [`autoload`](https://getcomposer.org/doc/04-schema.md#autoload) in their `composer.json`.

`imposter` relies on those `autoload` fields.

Unfortunately, `imposter` is not the solution for your use case. Try the [alternatives](https://github.com/TypistTech/imposter#alternatives)

related: https://github.com/TypistTech/imposter/issues/57

**Comment by Luc45** [comment]
Oh yeah. I am using a VCS repository. I have excluded that one specifically and it worked fine. Thanks!
